/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AnalogClock {
        /**
          * Time to be displayed in the clock.
         */
        "time": number;
        /**
          * Timezone in which the date and time should be shown. Default is browser timezone.
         */
        "timeZone": string;
    }
    interface DateTime {
        /**
          * Should the time keep updating. Default is `false`
         */
        "shouldUpdate": boolean;
        /**
          * Should the clock be shown. Default is `false`
         */
        "showClock": boolean;
        /**
          * Timezone in which the date and time should be shown. Default is browser timezone.
         */
        "timeZone": string;
    }
}
declare global {
    interface HTMLAnalogClockElement extends Components.AnalogClock, HTMLStencilElement {
    }
    var HTMLAnalogClockElement: {
        prototype: HTMLAnalogClockElement;
        new (): HTMLAnalogClockElement;
    };
    interface HTMLDateTimeElement extends Components.DateTime, HTMLStencilElement {
    }
    var HTMLDateTimeElement: {
        prototype: HTMLDateTimeElement;
        new (): HTMLDateTimeElement;
    };
    interface HTMLElementTagNameMap {
        "analog-clock": HTMLAnalogClockElement;
        "date-time": HTMLDateTimeElement;
    }
}
declare namespace LocalJSX {
    interface AnalogClock {
        /**
          * Time to be displayed in the clock.
         */
        "time"?: number;
        /**
          * Timezone in which the date and time should be shown. Default is browser timezone.
         */
        "timeZone"?: string;
    }
    interface DateTime {
        /**
          * Should the time keep updating. Default is `false`
         */
        "shouldUpdate"?: boolean;
        /**
          * Should the clock be shown. Default is `false`
         */
        "showClock"?: boolean;
        /**
          * Timezone in which the date and time should be shown. Default is browser timezone.
         */
        "timeZone"?: string;
    }
    interface IntrinsicElements {
        "analog-clock": AnalogClock;
        "date-time": DateTime;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "analog-clock": LocalJSX.AnalogClock & JSXBase.HTMLAttributes<HTMLAnalogClockElement>;
            "date-time": LocalJSX.DateTime & JSXBase.HTMLAttributes<HTMLDateTimeElement>;
        }
    }
}
